### ISSUE TITLE
Visualization TODO

### ISSUE THREAD

**Issue by muziejus** [un-silencing-slavery-at-rose-hall/project-website#1]
- [x] Scale Bar
- [x] Reorder/recolor petals based on criteria (family, race…)
- [x] Fixup/investigate person card animation.
- [x] Check how things look on the phone
- [x] Make pie chart legend clearer and integrate age scale bar with a general legend widget
- [x] Integrate category legend via toast or maybe tippy.
- [x] Hover tooltip on categories include glossary definition (if applicable) and numerical information (number of ppl in category and percentage of whole)
- [x] Add sort key as heading for visualization per Monique's suggestion
