### ISSUE TITLE
Documents TODO

### ISSUE THREAD

**Issue by muziejus** [un-silencing-slavery-at-rose-hall/project-website#2]
Create a digital collection / Wax site that includes the archival material, etc. Build with a base url of `/archive`.

- [x] Inherit CSS from Ember and/or figure that part out. (Ember puts the styles in `/assets/rose-hall.css`)
- [x] Ask @muziejus how to build an Ember app on my computer.

**Comment by muziejus** [comment]
- [ ] csv has to be kosher
- [x] acquire the archival images

**Comment by muziejus** [comment]
For @elotroalex:

- [ ] look at Celia's email and update documents 
- [x] Convert to 2-col layout on desktop/ipad and 1-col layout
- [x] Add biblio links like https://doi.org/10.1215/07990537-1334212 for "Out and Bad"
- [x] Solve redundant text accompanying thumbnails of documents.

**Comment by muziejus** [comment]
for @muziejus 

- [x] Break up intro to documents to add subheadings

**Comment by elotroalex** [comment]
What does "csv has to be kosher mean" above?
