### ISSUE TITLE
Reflections TODO

### ISSUE THREAD

**Issue by muziejus** [un-silencing-slavery-at-rose-hall/project-website#4]
@elotroalex will meet with Celia to discuss the essay.

**Comment by muziejus** [comment]
- [x] move historical essay to about
- [x] solicit reflections from contributors
- [x] change name of "Essay" in navbar to "reflections"
- [x] add essay titles.
- [x] add community tree image to essay / about

**Comment by muziejus** [comment]
Celia's reflection:

https://docs.google.com/document/d/1_ht1FW4ZyDTdu1krVUw1ZPQbSAsMOWLHi4InAhl5qiE/edit?usp=sharing
