### ISSUE TITLE
Information TODO

### ISSUE THREAD

**Issue by muziejus** [un-silencing-slavery-at-rose-hall/project-website#7]
- [x] Create headers in list for each sort term
- [x] Add disclosure triangles for categories
- [x] Add disclosure triangles for mothers
- [ ] Convert hover popups to toasts.
- [x] Give "active" class to glossary link when clicked, attach to visibility of toast.
- [x] Reduce size of `display_name` (keep bottom padding but change text to text-2xl)
- [ ]
